### ISSUE TITLE
RPi + camera for dev work

### ISSUE THREAD

**Issue by ebgoldstein** [NCRoadNetworks/PiCamML#9]
To deploy the ML models on a RPi, we will want a device to do dev work. My suggestion is to use a device that looks/functions exactly like the cameras/gateways already in existence. 

@anardek , is there a built RPi camera/gateway that can be used for this, or does @rtmccune need to fabricate a new one? (and a reminder that we do have funding for these supplies)

**Comment by anardek** [comment]
I believe we have a working gateway downstairs in the lab that he can use.
I will confirm with Thomas.

**Comment by anardek** [comment]
Ok, we have two gateways that are working and ready for each of you. Our awesome undergrad Harper turned off the PT communication today, so now the gateway solely operates as a real-time camera. You will have to follow the Sunny Day Flooding Tutorials in order to connect it to a wifi network or change any settings.

@ebgoldstein -- are you coming this way anytime soon? Otherwise maybe Ryan and I can make a trip up to Greensboro in the next month or so.

**Comment by anardek** [comment]
Also, @rtmccune -- your gateway is ready whenever you need it. I suggest you go and take it and put it at your desk or something so it doesn't get swiped for another location.

**Comment by ebgoldstein** [comment]
done
